<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOrqj2rA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOrqj2rA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOrqj2rA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOrqj2rA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOrqj2rA\App_KernelDevDebugContainer([
    'container.build_hash' => 'Orqj2rA',
    'container.build_id' => 'ecc3e58d',
    'container.build_time' => 1604460149,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOrqj2rA');
