<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDdtPxdS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDdtPxdS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDdtPxdS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDdtPxdS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDdtPxdS\App_KernelDevDebugContainer([
    'container.build_hash' => 'DdtPxdS',
    'container.build_id' => 'eac0c101',
    'container.build_time' => 1603936291,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDdtPxdS');
